services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    container_name: pblgllgs-api
    image: pblgllgs/pblgllgs-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

networks:
  db:
    driver: bridge

volumes:
  db: