services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  backend:
    container_name: pblgllgs-api
    image: pblgllgs/pblgllgs-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

  frontend:
    container_name: frontend-fsa
    image: pblgllgs/frontend-fsa:latest
    ports:
      - "80:80"
    networks:
      - db
    depends_on:
      - backend
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: